# Based off https://github.com/starkat99/appveyor-rust

image: 
- Visual Studio 2017
- Visual Studio 2019

platform:
- x86
- x64

# Default to VS2019, x64
environment:
  vs_ver: 2019
  vs_vars: vcvars64.bat
  target: x86_64-pc-windows-msvc
  channel: stable

for:
-
  # Override for VS2017
  matrix:
    only:
      - image: Visual Studio 2017
  environment:
    vs_ver: 2017
-
  # Override for x86
  matrix:
    only:
      - platform: x86
  environment:
    target: i686-pc-windows-msvc
    vs_vars: vcvars32.bat

install:
  # Visual Studio developer environment for x86/x64
  # https://www.appveyor.com/docs/lang/cpp/#visual-studio
  - set VS_VARS="C:\Program Files (x86)\Microsoft Visual Studio\%vs_ver%\Community\VC\Auxiliary\Build\%vs_vars%"
  - echo %VS_VARS%
  - call %VS_VARS%
  # Download rustup and install rust
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV
  # Checkout submodules
  - git submodule update --init --recursive

# Skip build step since `cargo test` does it
build: false

test_script:
- ps: .\build.ps1
