
trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.14'
    vs2017:
      imageName: 'vs2017-win2016'
    # vs2019:
    #   imageName: 'windows-2019'

pool:
  vmImage: $(imageName)

steps:
- checkout: self
  submodules: recursive
- pwsh: ./scripts/install_rust.ps1
  displayName: 'Installing Rust'
- pwsh: ./build.ps1
  displayName: 'Building/Testing'
